"""empty message

Revision ID: 1274a925c01b
Revises: 3c5a7e50a629
Create Date: 2014-09-28 17:57:45.742963

"""

# revision identifiers, used by Alembic.
revision = '1274a925c01b'
down_revision = '3c5a7e50a629'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('tag', sa.Column('hidden', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'hidden')
    op.drop_column('category', 'hidden')
    ### end Alembic commands ###
