"""Initial commit

Revision ID: 127682c11a74
Revises: 3c5a7e50a629
Create Date: 2014-09-28 18:39:53.592751

"""

# revision identifiers, used by Alembic.
revision = '127682c11a74'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
