"""empty message

Revision ID: 3c5a7e50a629
Revises: None
Create Date: 2014-09-28 17:54:15.231834

"""

# revision identifiers, used by Alembic.
revision = '3c5a7e50a629'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
