"""empty message

Revision ID: 591f74b599d5
Revises: 1a8ee645def6
Create Date: 2016-05-08 21:20:38.759813

"""

# revision identifiers, used by Alembic.
revision = '591f74b599d5'
down_revision = '1a8ee645def6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('template', sa.String(255)))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'template')
    ### end Alembic commands ###
